### ISSUE TITLE
ImportError: cannot import name 'VectorStore' from 'langchain.vectorstores'

### ISSUE THREAD

**Issue by yiouyou** [whitead/paper-qa#199]
In doc.py line 17:

from langchain.vectorstores import FAISS, VectorStore

cause import error with langchain latest version.

Anyway to quick fix this?

Thanks!

**Comment by Amejonah1200** [comment]
I had the same problem, I just edited the code so it points to the right class 🤪

**Comment by johannrichard** [comment]
This is due to a change in `langchain` in v0.0.324+. The highest compatible version of `langchain` that still works with `paper-qa` as is v0.0.323. 

You can fix the langchain version when installing `paper-qa`like this:

```code=bash
pip install paper-qa langchain==0.0.323 
```

**Comment by whitead** [comment]
Fixed by #201
